"""create agent_request_logs table

Revision ID: 1d98858db855
Revises:
Create Date: 2025-11-23 12:35:43.147088

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1d98858db855"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_request_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("raw_command", sa.String(length=512), nullable=False),
        sa.Column("is_success", sa.Boolean(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("executed_command", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_request_logs")
    # ### end Alembic commands ###
